### PR TITLE
[adm-3a] fix load-cursor function (closes #147)

### LINKED ISSUE #147: [ADM-3A] Software controlled cursor
Hello,
First of all, thank you for creating this software.
I've ran into an issue with ADM-3A and its load-cursor function.
I can see that it's implemented with the keyboard, the `ESC = Y X`, but it is also possible when sending that sequence to the port, at least in theory.
Here's the documentation I found: http://bitsavers.informatik.uni-stuttgart.de/www.computer.museum.uq.edu.au/pdf/DP-104%20ADM-3A%20Operators%20Manual.pdf
It would be also nice to have hardware switches implemented.

I wrote a hotfix, but I wanted to share, because I don't know a proper place to put this in.
```patch
diff --git a/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java b/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java
index 7a5ce0c9..ab551cc7 100644
--- a/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java
+++ b/plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/Display.java
@@ -65,6 +65,9 @@ public class Display extends JPanel implements DeviceContext<Short>, TerminalSet
 
     private FileWriter outputWriter = null;
 
+    private int loadCursorActive = 0;
+    private int loadCursorY = -1;
+
     public Display(Cursor cursor, TerminalSettings settings) {
         this.settings = Objects.requireNonNull(settings);
         this.cursor = Objects.requireNonNull(cursor);
@@ -292,6 +295,28 @@ public class Display extends JPanel implements DeviceContext<Short>, TerminalSet
          * if it is special char, interpret it. else just add
          * to "video memory"
          */
+
+        // Implement load-cursor from code
+        switch (loadCursorActive) {
+            case 1:
+                if (data != '=') {
+                    loadCursorActive = 0;
+                }
+                else {
+                    loadCursorActive = 2;
+                }
+                return;
+            case 2:
+                loadCursorY = data - 32;
+                loadCursorActive = 3;
+                return;
+            case 3:
+                cursor.set(data - 32, loadCursorY);
+                loadCursorActive = 0;
+                repaint();
+                return;
+        }
+
         switch (data) {
             case 5: // HERE IS
                 insertString(HERE_IS_CONSTANT);
@@ -320,6 +345,7 @@ public class Display extends JPanel implements DeviceContext<Short>, TerminalSet
                 clearScreen();
                 return;
             case 0x1B: // initiates load cursor operation
+                loadCursorActive = 1;
             case 0x1E: // homes cursor
                 cursor.home();
                 break;

```

### PR DESCRIPTION
**Pull request by MarcinWieczorek**
As discussed in #147

### CODE REVIEW

File: plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/LoadCursorPosition.java [hunk 1]
```diff
@@ -19,135 +19,65 @@
...
-                    cursor.set(cursorPos, cursorPos);
-                } else {
-                    cursor.set(cursorPos, cursor.getPoint().y);
-                }
+            expect = Y;
+            return true;
+        } else if (expect == Y) {
+            if (!checkBounds(data)) {
+                expect = ESCAPE;
+                return true;
```
Comment (vbmacher) [inline plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/LoadCursorPosition.java]: Here I would return false. If the character is out of bounds, the sequence is not "accepted" and the character should be normally displayed.

File: plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/LoadCursorPosition.java [hunk 2]
```diff
@@ -19,135 +19,65 @@
...
             }
+
+            cursorY = data - ASCII_COORDINATE_OFFSET;
+            expect = X;
+            return true;
+        } else if (expect == X) {
+            int cursorX = data - ASCII_COORDINATE_OFFSET;
+
+            if (checkBounds(data)) {
```
Comment (vbmacher) [inline plugins/devices/adm3A-terminal/src/main/java/net/sf/emustudio/devices/adm3a/impl/LoadCursorPosition.java]: Here maybe the same thing - if `checkBounds` returns `false`, then the sequence is not accepted and the method should return `false`.
